add LT
CosmicMedia/vanillo-i18n pull request #3
Opened 2023-12-18 11:09 UTC by dw5

2023-12-18 17:20 UTC, TheRandomMelon requested changes
Unless it was intentional, the untranslated strings should be translated before this is merged.

2023-12-18 17:20 UTC, TheRandomMelon commented on languages/lt.json
> +      "creator_news_soon": "Creator News is coming soon!",
I assume this was an accident? Your previous commit had translations for creator_news, creator_news_soon, etc

2023-12-20 07:35 UTC, dw5 commented
fixed, plus some lines lacked `,` at the end.
did not have luck seeing lt in i18n-ally

2023-12-20 18:40 UTC, BlakeB415 commented
Thank you so much!

2023-12-20 18:40 UTC, merged

2023-12-20 18:42 UTC, TheRandomMelon commented
Seems good to me now